### ISSUE TITLE
404 page broken

### ISSUE THREAD

**Issue by cesarvarela** [netlify/gatsby-plugin-netlify#101]
HI, we are getting errors when navigating to an inexistent route instead of getting a 404:
```
{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '/var/task/site/gatsby-site/.cache/page-ssr'\nRequire stack:\n- /var/task/site/gatsby-site/.netlify/functions-internal/__dsg/__dsg.js\n- /var/task/__dsg.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","trace":["Runtime.ImportModuleError: Error: Cannot find module '/var/task/site/gatsby-site/.cache/page-ssr'","Require stack:","- /var/task/site/gatsby-site/.netlify/functions-internal/__dsg/__dsg.js","- /var/task/__dsg.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:202:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1085:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","    at Module.load (internal/modules/cjs/loader.js:950:32)","    at Function.Module._load (internal/modules/cjs/loader.js:790:12)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)","    at internal/main/run_main_module.js:17:47"]}
```
Tested with `"gatsby-plugin-netlify": "^4.1.0",`

Project is here: https://github.com/responsible-ai-collaborative/aiid

**Comment by cesarvarela** [comment]
I guess it is being tracked here: https://github.com/netlify/netlify-plugin-gatsby/issues/330

**Comment by ascorbic** [comment]
Hi @cesarvarela 
Yes, thanks for the report. We have a fix, which should be out shortly.
